from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]
init = { changelog_title = "Initial Commit", omit_from_changelog = true }
release = { changelog_title = "Releases" }


[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "passwrd"
owner = "fURL-web"
authors = [
  { signature = "The Bearodactyl", username = "thebearodactyl" }
]

[bump_profiles]

[packages]
